<?php

declare(strict_types=1);
require_once __DIR__ . '/bootstrap.php';
function drive_connection(): ?array { $r=db()->query('SELECT * FROM drive_connections WHERE id=1 LIMIT 1')->fetch();return $r?:null; }
function drive_authorize_url(): string { return 'https://accounts.google.com/o/oauth2/v2/auth?'.http_build_query(['client_id'=>GOOGLE_CLIENT_ID,'redirect_uri'=>GOOGLE_REDIRECT_URI,'response_type'=>'code','scope'=>'https://www.googleapis.com/auth/drive.readonly','access_type'=>'offline','prompt'=>'consent','state'=>csrf_token()]); }
function http_form(string $endpoint,array $fields): array { $c=curl_init($endpoint);curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($fields),CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded'],CURLOPT_TIMEOUT=>60]);$b=curl_exec($c);$s=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);$e=curl_error($c);curl_close($c);if($b===false||$s>=400)throw new RuntimeException('OAuth ผิดพลาด: '.($e?:(string)$b));return json_decode((string)$b,true,512,JSON_THROW_ON_ERROR); }
function drive_exchange_code(string $code): array { return http_form('https://oauth2.googleapis.com/token',['code'=>$code,'client_id'=>GOOGLE_CLIENT_ID,'client_secret'=>GOOGLE_CLIENT_SECRET,'redirect_uri'=>GOOGLE_REDIRECT_URI,'grant_type'=>'authorization_code']); }
function drive_save_token(array $token): void { $old=drive_connection();$refresh=$token['refresh_token']??($old['refresh_token']??null);$s=db()->prepare('INSERT INTO drive_connections(id,access_token,refresh_token,expires_at,created_at,updated_at) VALUES(1,?,?,?,?,NOW()) ON DUPLICATE KEY UPDATE access_token=VALUES(access_token),refresh_token=VALUES(refresh_token),expires_at=VALUES(expires_at),updated_at=NOW()');$s->execute([$token['access_token']??'',$refresh,date('Y-m-d H:i:s',time()+(int)($token['expires_in']??3600)),date('Y-m-d H:i:s')]); }
function drive_access_token(): string { $d=drive_connection();if(!$d)throw new RuntimeException('ยังไม่ได้เชื่อมต่อ Google Drive');if($d['access_token']&&strtotime((string)$d['expires_at'])>time()+60)return (string)$d['access_token'];if(!$d['refresh_token'])throw new RuntimeException('ไม่พบ Refresh token');$t=http_form('https://oauth2.googleapis.com/token',['client_id'=>GOOGLE_CLIENT_ID,'client_secret'=>GOOGLE_CLIENT_SECRET,'refresh_token'=>$d['refresh_token'],'grant_type'=>'refresh_token']);db()->prepare('UPDATE drive_connections SET access_token=?,expires_at=?,updated_at=NOW() WHERE id=1')->execute([$t['access_token'],date('Y-m-d H:i:s',time()+(int)($t['expires_in']??3600))]);return (string)$t['access_token']; }
function drive_request(string $endpoint): array { $c=curl_init($endpoint);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.drive_access_token(),'Accept: application/json'],CURLOPT_TIMEOUT=>90]);$b=curl_exec($c);$s=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);$e=curl_error($c);curl_close($c);if($b===false||$s>=400)throw new RuntimeException('Google Drive API ผิดพลาด: '.($e?:(string)$b));return json_decode((string)$b,true,512,JSON_THROW_ON_ERROR); }
function drive_list_images(string $folderId): array { $files=[];$page=null;do{$p=['q'=>sprintf("'%s' in parents and trashed=false and mimeType contains 'image/'",str_replace("'","\\'",$folderId)),'fields'=>'nextPageToken,files(id,name,mimeType,size,modifiedTime)','pageSize'=>1000,'supportsAllDrives'=>'true','includeItemsFromAllDrives'=>'true','orderBy'=>'name'];if($page)$p['pageToken']=$page;$d=drive_request('https://www.googleapis.com/drive/v3/files?'.http_build_query($p));$files=array_merge($files,$d['files']??[]);$page=$d['nextPageToken']??null;}while($page);return $files; }
function drive_download(string $fileId,string $destination): void { $c=curl_init('https://www.googleapis.com/drive/v3/files/'.rawurlencode($fileId).'?alt=media&supportsAllDrives=true');$fp=fopen($destination,'wb');if(!$fp)throw new RuntimeException('สร้างไฟล์ปลายทางไม่สำเร็จ');curl_setopt_array($c,[CURLOPT_HTTPHEADER=>['Authorization: Bearer '.drive_access_token()],CURLOPT_FILE=>$fp,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_TIMEOUT=>300]);$ok=curl_exec($c);$s=(int)curl_getinfo($c,CURLINFO_RESPONSE_CODE);$e=curl_error($c);curl_close($c);fclose($fp);if(!$ok||$s>=400){@unlink($destination);throw new RuntimeException('ดาวน์โหลดรูปไม่สำเร็จ: '.($e?:'HTTP '.$s));} }
